version: "3.8"
services:
    docker_postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: Yatathakar123!
            POSTGRES_USER: qj
            POSTGRES_DB: quranJourney
            PGDATA: pgdata
        volumes:
            - ./pgdata:/var/lib/postgresql/qj:z
            - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql:z
            - ./db/quran-simple.sql:/docker-entrypoint-initdb.d/quran-simple.sql:z
        command: -p 5433
        ports:
            - "5433:5432"
        networks:
            - default
    qj:
        build: .
        depends_on:
            - docker_postgres
        ports:
            - "3001:3001"
        networks:
            - default
